#!/usr/bin/env node

import * as cp from "node:child_process";
import * as fs from "node:fs";
import path from "node:path";
import * as url from "node:url";

const dirname = path.dirname(url.fileURLToPath(import.meta.url));
const commandDirectory = path.join(dirname, "./commands/");
const commandFiles = (await fs.promises.readdir(commandDirectory)).map(
  (file) => {
    return path.join(commandDirectory, file);
  },
);

const configTemplate = `
# {{url}}

gui:
{{template}}

customCommands:
{{commands}}
`;

const themes = {
  "./themes/latte.yml": `https://raw.githubusercontent.com/catppuccin/lazygit/refs/heads/main/themes/latte/red.yml`,
  "./themes/mocha.yml": `https://raw.githubusercontent.com/catppuccin/lazygit/refs/heads/main/themes/mocha/red.yml`,
};

/**
 * @param {string} path
 * @param {string} url
 * @param {string[]} commands
 */
async function downloadTemplate(path, url, commands) {
  const template = indent(cp.execSync(`curl ${url}`, { encoding: "utf8" }));

  await fs.promises.writeFile(
    path,
    configTemplate
      .replace("{{url}}", url)
      .replace("{{template}}", template)
      .replace("{{commands}}", commands.join("\n")),
  );
}

/** @param {string} lines  */
function indent(lines, indentation = 2) {
  return lines
    .split("\n")
    .map((line) => " ".repeat(indentation) + line)
    .join("\n");
}

const commands = await Promise.all(
  commandFiles.map(async (filename) => {
    const file = await fs.promises.readFile(filename, "utf8");
    return indent(file);
  }),
);

await Promise.all(
  Object.entries(themes).map(async ([path, url]) => {
    await downloadTemplate(path, url, commands);
  }),
);
