#!/usr/bin/env node

import * as cp from 'node:child_process'
import * as fs from 'node:fs'

const files = {
	"./themes/latte.yml": "https://raw.githubusercontent.com/catppuccin/lazygit/refs/heads/main/themes/latte/red.yml",
	"./themes/mocha.yml": "https://raw.githubusercontent.com/catppuccin/lazygit/refs/heads/main/themes/mocha/red.yml"
}

function downloadTemplate(path, url) {
	const template = cp.execSync(`curl ${url}`, { encoding: "utf8" })
		.split('\n')
		.map((line) => '  ' + line)
		.join('\n')

	fs.writeFileSync(path, `
# ${url}
gui:
${template}`
	)
}

for (const [path, url] of Object.entries(files)) {
	downloadTemplate(path, url)
}
